# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EIA_Map_Production_Automation
                                 A QGIS plugin
 Plugin to automate production of all maps for environmental impact assesments
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-07-21
        git sha              : $Format:%H$
        copyright            : (C) 2020 by WSP
        email                : chris.ryan@wsp.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

#old imports needs tidy

import sys
import os
import processing
import time
import shutil

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from qgis.gui import *
from qgis.utils import iface
from PyQt5.QtWidgets import *
from qgis.core import *


# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .EIA_Map_Production_Automation_dialog import EIA_Map_Production_AutomationDialog
import os.path


class EIA_Map_Production_Automation:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'EIA_Map_Production_Automation_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&EIA_Map_Production_Automation')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('EIA_Map_Production_Automation', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/EIA_Map_Production_Automation/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&EIA_Map_Production_Automation'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = EIA_Map_Production_AutomationDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass

            # 1.creating sub folders in input project directory

            if result:
                projectfolder = self.dlg.Proj_Folder.text()

                projectGISFolder = projectfolder + "\\" + "EIA Constraints Map Production"
                folders = ["1. Site Location Shapefile", "2.Project Buffers", "3. Clipped Outputs",
                           "4. QGIS Map Docs", "5. Map Outputs"]
            try:
                path = projectGISFolder
                os.makedirs(path, 493)
            except:
                print("error")
            try:
                for folder in folders:
                    path = projectGISFolder + "\\" + folder
                    os.makedirs(path, 493)
            except:
                print("error")


            # ----------------Clipped folder---------------------------------------------------------

            if result:
                Clipped_Sub_Folder = projectGISFolder + "\\" + folders[2] + "\\"
                Sub_Folder = Clipped_Sub_Folder + "\\" + "Clipped Constraints 200m"
                CC_200m = ["Clipped Constraints 200m"]
            try:
                path = Sub_Folder
                os.makedirs(path, 493)
            except:
                print("error")

            if result:
                Clipped_Sub_Folder = projectGISFolder + "\\" + folders[2] + "\\"
                Sub_Folder = Clipped_Sub_Folder + "\\" + "Clipped Constraints 500m"
                CC_500m = ["Clipped Constraints 500m"]
            try:
                path = Sub_Folder
                os.makedirs(path, 493)
            except:
                print("error")
            if result:
                Clipped_Sub_Folder_= projectGISFolder + "\\" + folders[2] + "\\"
                Sub_Folder = Clipped_Sub_Folder + "\\" + "Clipped Constraints 600m"
                CC_600m = ["Clipped Constraints 600m"]
            try:
                path = Sub_Folder
                os.makedirs(path, 493)
            except:
                print("error")
            if result:
                Clipped_Sub_Folder_= projectGISFolder + "\\" + folders[2] + "\\"
                Sub_Folder = Clipped_Sub_Folder + "\\" + "Clipped Constraints 1000m"
                CC_1000m = ["Clipped Constraints 1000m"]
            try:
                path = Sub_Folder
                os.makedirs(path, 493)
            except:
                print("error")

           #--------------------------------------------------------------------------------

            # creating buffers

            Buffer_Folder = projectGISFolder + "\\" + folders[1] + "\\"

            Buff200 = Buffer_Folder + "\\" + "Site Location 200m Buffer.shp"
            Buff500 = Buffer_Folder + "\\" + "Site Location 500m Buffer.shp"
            Buff600 = Buffer_Folder + "\\" + "Site Location 600m Buffer.shp"
            Buff1000 = Buffer_Folder + "\\" + "Site Location 1000m Buffer.shp"


            processing.run("native:buffer",
                           {'INPUT': 'E:\\EIA\\Data\\Mock centerline\\Mock_centerline.shp', 'DISTANCE': 200,
                            'SEGMENTS': 5, 'END_CAP_STYLE': 0, 'JOIN_STYLE': 0, 'MITER_LIMIT': 2, 'DISSOLVE': True,
                            'OUTPUT': Buff200})
            processing.run("native:buffer",
                           {'INPUT': 'E:\\EIA\\Data\\Mock centerline\\Mock_centerline.shp', 'DISTANCE': 500,
                            'SEGMENTS': 5, 'END_CAP_STYLE': 0, 'JOIN_STYLE': 0, 'MITER_LIMIT': 2, 'DISSOLVE': True,
                            'OUTPUT': Buff500})
            processing.run("native:buffer",
                           {'INPUT': 'E:\\EIA\\Data\\Mock centerline\\Mock_centerline.shp', 'DISTANCE': 600,
                            'SEGMENTS': 5, 'END_CAP_STYLE': 0, 'JOIN_STYLE': 0, 'MITER_LIMIT': 2, 'DISSOLVE': True,
                            'OUTPUT': Buff600})
            processing.run("native:buffer",
                           {'INPUT': 'E:\\EIA\\Data\\Mock centerline\\Mock_centerline.shp', 'DISTANCE': 1000,
                            'SEGMENTS': 5, 'END_CAP_STYLE': 0, 'JOIN_STYLE': 0, 'MITER_LIMIT': 2, 'DISSOLVE': True,
                            'OUTPUT': Buff1000})


            # ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
            # Clipping Layers to buffers

            clip_output_200m = Clipped_Sub_Folder + "\\" + CC_200m[0] + "\\"
            clip_output_500m = Clipped_Sub_Folder + "\\" + CC_500m[0] + "\\"
            clip_output_600m = Clipped_Sub_Folder + "\\" + CC_600m[0] + "\\"
            clip_output_1km = Clipped_Sub_Folder + "\\" + CC_1000m[0] + "\\"

            EIA_Data = r'\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\EIA Datastore' + "\\"


            # Clipping Constraints to buffer distances:

            datalist = []
            for item in os.listdir(EIA_Data):
                if item[-3:] == 'shp':
                    datalist.append(item)

            for layer in datalist:
                processing.run("native:clip",
                               {'INPUT': EIA_Data + layer,
                                'OVERLAY': Buff200,
                                'OUTPUT': clip_output_200m + layer})
                processing.run("native:clip",
                               {'INPUT': EIA_Data + "\\" + layer,
                                'OVERLAY': Buff500,
                                'OUTPUT': clip_output_500m + layer})
                processing.run("native:clip",
                               {'INPUT': EIA_Data + "\\" + layer,
                                'OVERLAY': Buff600,
                                'OUTPUT': clip_output_600m + layer})
                processing.run("native:clip",
                               {'INPUT': EIA_Data + "\\" + layer,
                                'OVERLAY': Buff1000,
                                'OUTPUT': clip_output_1km + layer})


           #-----------------------------------------------------------------------------------------------------------------------------------------------------

            # importing symbology into output shapefile folders:
            main_symbol_folder = r'\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\EIA Datastore\QML Symbols'
            main_symbols_list = []
            for symbols in os.listdir(main_symbol_folder):
                if symbols[-3:] == 'qml':
                    main_symbols_list.append(main_symbol_folder + "\\" + symbols)
            for ms in main_symbols_list:
                shutil.copy(ms, clip_output_200m),
                shutil.copy(ms, clip_output_500m),
                shutil.copy(ms, clip_output_600m),
                shutil.copy(ms, clip_output_1000m),


            Walk10_symbol_folder = r'\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\Active Travel Zones\QML Symbols\Isochrone\10 Min Walk'
            Cycle10_symbol_folder = r'\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\Active Travel Zones\QML Symbols\Isochrone\10 Min Cycle'
            Cycle20_symbol_folder = r'\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\Active Travel Zones\QML Symbols\Isochrone\20 Min Cycle'
            Site_symbol_folder = r'\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\Active Travel Zones\QML Symbols\Site'
            site_symbols_list = []
            walk10_symbols_list = []
            cycle10_symbols_list = []
            cycle20_symbols_list = []

            for w10 in os.listdir(Walk10_symbol_folder):
                if w10[-3:] == 'qml':
                    walk10_symbols_list.append(Walk10_symbol_folder + "\\" + w10)
                for w10symbol in walk10_symbols_list:
                    shutil.copy(w10symbol, Ten_Minute_Walk_Sub_Folder),

            for c10 in os.listdir(Cycle10_symbol_folder):
                if c10[-3:] == 'qml':
                    cycle10_symbols_list.append(Cycle10_symbol_folder + "\\" + c10)
                for c10symbol in cycle10_symbols_list:
                    shutil.copy(c10symbol, Ten_Minute_Cycle_Sub_Folder),

            for c20 in os.listdir(Cycle20_symbol_folder):
                if c20[-3:] == 'qml':
                    cycle20_symbols_list.append(Cycle20_symbol_folder + "\\" + c20)
                for c20symbol in cycle20_symbols_list:
                    shutil.copy(c20symbol, Twenty_Minute_Cycle_Sub_Folder),

            for s in os.listdir(Site_symbol_folder):
                if s[-3:] == 'qml':
                    site_symbols_list.append(Site_symbol_folder + "\\" + s)
                for s_symbol in site_symbols_list:
                    shutil.copy(s_symbol, BNG_Converted_Point_Folder),

            # ---Map names ----------------------------------------------------------
            Map1name = "Map 1 - Site"
            Map2name = "Map 2 - Neighbourhood & Most Important Journey.qgs"
            Map3name = "Map 3 - Neighbourhood Safety.qgs"

            # ----------Creating Map 1----------------------------------------------------------------------------------------

            Mapout = projectGISFolder + "\\" + folders[3] + "\\"
            project1 = QgsProject.instance()
            project1.setCrs(QgsCoordinateReferenceSystem(3857))
            project1.setFileName(Mapout + Map1name)

            MapSite = BNG_Sub_Folder_make + BNGFOLDER[0] + "\\" + "Site Location.shp"
            Map1Layers = projectGISFolder + "\\" + folders[2] + "\\" + CLIP_CYCLE_20[0] + "\\"

            # Map1Layers = Walk_10_service_area_clip
            Site = QgsVectorLayer(MapSite, "Site", "ogr")
            Cycle_10_Map = QgsVectorLayer(CH_CYCLE_10, "Approximate 10 minute cycle time from site", "ogr")
            Cycle_20_Map = QgsVectorLayer(CH_CYCLE_20, "Approximate 20 minute cycle time from site", "ogr")

            mapbox_basemap = 'type=xyz&url=https://api.mapbox.com/styles/v1/chris-ryan-wsp/ck3r54pn8041b1cmzvdaxv1qc/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoiY2hyaXMtcnlhbi13c3AiLCJhIjoiY2szazRzNnhqMG8xZTNjb2N5NDVqeTV5MSJ9.hpX0Il1EIUT5pc7v-Z7lSQ'
            rlayer = QgsRasterLayer(mapbox_basemap, 'Mapbox', 'wms')
            QgsProject.instance().addMapLayer(rlayer)

            Layerlist = []
            for item in os.listdir(Map1Layers):
                if item[-3:] == 'shp':
                    Layerlist.append(item)
            for layer in Layerlist:
                shplayer = iface.addVectorLayer(Map1Layers + "//" + layer, "", "ogr")
                shplayer.setCrs(QgsCoordinateReferenceSystem(27700))
                project1.addMapLayer(shplayer)

            project1.addMapLayer(Site)
            project1.addMapLayer(Cycle_20_Map)
            project1.addMapLayer(Cycle_10_Map)
            ex = Cycle_20_Map.extent()

            # transforms layer projection

            proj = QgsProject.instance()
            if Site.crs().authid() != proj.crs().authid():
                tr = QgsCoordinateTransform(Site.crs(), proj.crs(), proj)
                ex = tr.transform(ex)
            if shplayer.crs().authid() != proj.crs().authid():
                tr = QgsCoordinateTransform(shplayer.crs(), proj.crs(), proj)

            Layermap = QgsProject.instance().mapLayers()
            RemoveLayers = []
            for name, layer in Layermap.items():
                if layer.isValid():
                    if layer.type() == QgsMapLayer.VectorLayer:
                        if layer.featureCount() == 0:
                            RemoveLayers.append(layer.id())
            if len(RemoveLayers) > 0:
                QgsProject.instance().removeMapLayers(RemoveLayers)
                # Add a small space/border on each side of the layer
                hborder = ex.height() / 70
                wborder = ex.width() / 70
                ex.set(ex.xMinimum() - wborder,
                       ex.yMinimum() - hborder,
                       ex.xMaximum() + wborder,
                       ex.yMaximum() + hborder,
                       )

                iface.mapCanvas().setExtent(ex)

            # ------create map item in the layout_---------------------------------------------------------------------------------------------

            layers1 = QgsProject.instance().mapLayersByName('Site')
            layer1 = layers1[0]
            project = QgsProject.instance()
            manager = project.layoutManager()
            layoutName = 'Map 1: Active Travel Zones'
            layouts_list = manager.printLayouts()

            # removes dublicate layers produced
            for layout in layouts_list:
                if layout.name() == layoutName:
                    manager.removeLayout(layout)

            layout = QgsPrintLayout(project)
            layout.initializeDefaults()
            layout.setName(layoutName)

            manager.addLayout(layout)
            canvas = iface.mapCanvas()

            # Creating a frame around map and legend - min/max in mm in layout
            xmin = 5
            xmax = 292
            ymin = 2
            ymax = 208
            polygon = QPolygonF()
            polygon.append(QPointF(xmin, ymin))
            polygon.append(QPointF(xmax, ymin))
            polygon.append(QPointF(xmax, ymax))
            polygon.append(QPointF(xmin, ymax))

            # Create the polygon from nodes
            polygonItem = QgsLayoutItemPolygon(polygon, layout)

            # Add to the layout
            layout.addItem(polygonItem)

            # adding map to layout
            Map = QgsLayoutItemMap.create(layout)
            Map.setRect(10, 10, 210, 90)
            ms = QgsMapSettings()
            ms.setLayers([layer1])
            Map.setFrameEnabled(True)
            Map.setExtent(canvas.extent())
            Map.setScale(80000, forceUpdate=1)

            layout.addLayoutItem(Map)

            Map.attemptMove(QgsLayoutPoint(4, 2, QgsUnitTypes.LayoutMillimeters))
            # ============================(Width, Length)
            Map.attemptResize(QgsLayoutSize(215, 206, QgsUnitTypes.LayoutMillimeters))

            # addding custom arrow
            picture2 = QgsLayoutItemPicture(layout)
            picture2.update()
            layout.addLayoutItem(picture2)
            picture2.setPicturePath(
                r"\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\Active Travel Zones\Map Template Items\NorthArrow_Red.png")
            picture2.attemptMove(QgsLayoutPoint(5, 3, QgsUnitTypes.LayoutMillimeters))
            picture2.setResizeMode(QgsLayoutItemPicture.FrameToImageSize)

            # adding scalebar
            scalebar = QgsLayoutItemScaleBar(layout)
            scalebar.setStyle('Single Box')
            scalebar.setUnits(QgsUnitTypes.DistanceKilometers)
            scalebar.setNumberOfSegments(3)
            scalebar.setNumberOfSegmentsLeft(0)
            scalebar.setUnitsPerSegment(1)
            scalebar.setLinkedMap(Map)
            scalebar.setUnitLabel('km')
            scalebar.setFont(QFont('Arial', 8))
            scalebar.refresh()
            layout.addLayoutItem(scalebar)
            # ============================------(Width, Length)
            scalebar.attemptMove(QgsLayoutPoint(148, 196, QgsUnitTypes.LayoutMillimeters))
            scalebar.applyDefaultSize
            scalebar.refresh()

            # adding title
            title = QgsLayoutItemLabel(layout)
            title.setBackgroundEnabled(True)
            title.setText('Map 1: Active Travel Zones')
            title.setFont(QFont('Arial', 20))
            title.setFontColor(QColor('red'))
            title.adjustSizeToText()
            layout.addLayoutItem(title)
            # ============================---(Width, Length)
            title.attemptMove(QgsLayoutPoint(82, 3, QgsUnitTypes.LayoutMillimeters))
            title.refresh()

            # adding WSP logo
            picture = QgsLayoutItemPicture(layout)
            picture.update()
            layout.addLayoutItem(picture)
            picture.setPicturePath(
                r"\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\Active Travel Zones\Map Template Items\wsp_logo.png")
            picture.attemptMove(QgsLayoutPoint(5, 195, QgsUnitTypes.LayoutMillimeters))
            picture.setResizeMode(QgsLayoutItemPicture.FrameToImageSize)

            # adding legend and layers into legend
            legend = QgsLayoutItemLegend(layout)
            legend.setLinkedMap(Map)
            legend.refresh()
            layouts_check = QgsProject.instance().layoutManager()
            legend.setTitle("Key:")
            newFont = QFont("Aerial", 8)
            LargeFont = QFont("Aerial", 12)
            legend.setStyleFont(QgsLegendStyle.Title, LargeFont)
            legend.setStyleFont(QgsLegendStyle.Subgroup, newFont)
            legend.setStyleFont(QgsLegendStyle.SymbolLabel, newFont)
            layout.addLayoutItem(legend)

            # ============================---(Width, Length)
            legend.attemptMove(QgsLayoutPoint(221, 4, QgsUnitTypes.LayoutMillimeters))
            legend.attemptResize(QgsLayoutSize(15, QgsUnitTypes.LayoutMillimeters))
            legend.refresh()

            # ----- Export map as PDF and PNG--------------------------------

            OutMaps = projectGISFolder + "\\" + folders[4] + "\\"
            fn = OutMaps + "Map 1.Active Travel Zones.png"
            exporter = QgsLayoutExporter(layout)
            exporter.exportToImage(fn, QgsLayoutExporter.ImageExportSettings())

            # ------Map 1 completed---------------------

            # layout.refresh()
            project1.write()
            project1.clear()

            # ----------Creating Map 2----------------------------------------------------------------------------------------

            Mapout = projectGISFolder + "\\" + folders[3] + "\\"
            project2 = QgsProject.instance()
            project2.setCrs(QgsCoordinateReferenceSystem(27700))
            project2.setFileName(Mapout + Map2name)

            MapSite = BNG_Sub_Folder_make + BNGFOLDER[0] + "\\" + "Site Location.shp"
            Map2Layers = projectGISFolder + "\\" + folders[2] + "\\" + CLIP_CYCLE_10[0] + "\\"
            # Map1Layers = Walk_10_service_area_clip
            Site = QgsVectorLayer(MapSite, "Site", "ogr")
            Cycle_10_Map = QgsVectorLayer(CH_CYCLE_10, "Approximate 10 minute cycle time from site", "ogr")
            Walk_10_Map = QgsVectorLayer(CH_WALK_10, "Approximate 10 minute walk time from site", "ogr")

            mapbox_basemap = 'type=xyz&url=https://api.mapbox.com/styles/v1/chris-ryan-wsp/ck3r54pn8041b1cmzvdaxv1qc/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoiY2hyaXMtcnlhbi13c3AiLCJhIjoiY2szazRzNnhqMG8xZTNjb2N5NDVqeTV5MSJ9.hpX0Il1EIUT5pc7v-Z7lSQ'
            rlayer = QgsRasterLayer(mapbox_basemap, 'Mapbox', 'wms')
            QgsProject.instance().addMapLayer(rlayer)

            Layerlist2 = []
            print(Layerlist2)
            for item in os.listdir(Map2Layers):
                if item[-3:] == 'shp':
                    Layerlist2.append(item)
            for layer in Layerlist2:
                shplayer = iface.addVectorLayer(Map2Layers + "//" + layer, "", "ogr")
                shplayer.setCrs(QgsCoordinateReferenceSystem(27700))
                project2.addMapLayer(shplayer)

            project2.addMapLayer(Site)
            project2.addMapLayer(Cycle_10_Map)
            project2.addMapLayer(Walk_10_Map)
            ex = Cycle_10_Map.extent()

            # transforms layer projection

            proj = QgsProject.instance()
            if Site.crs().authid() != proj.crs().authid():
                tr = QgsCoordinateTransform(Site.crs(), proj.crs(), proj)
                ex = tr.transform(ex)
            if shplayer.crs().authid() != proj.crs().authid():
                tr = QgsCoordinateTransform(shplayer.crs(), proj.crs(), proj)
            Layermap = QgsProject.instance().mapLayers()
            RemoveLayers2 = []
            for name, layer in Layermap.items():
                if layer.isValid():
                    if layer.type() == QgsMapLayer.VectorLayer:
                        if layer.featureCount() == 0:
                            RemoveLayers2.append(layer.id())
            if len(RemoveLayers2) > 0:
                QgsProject.instance().removeMapLayers(RemoveLayers2)
            # Add a small space/border on each side of the layer
            hborder = ex.height() / 70
            wborder = ex.width() / 70
            ex.set(ex.xMinimum() - wborder,
                   ex.yMinimum() - hborder,
                   ex.xMaximum() + wborder,
                   ex.yMaximum() + hborder,
                   )
            iface.mapCanvas().setExtent(ex)
            iface.mapCanvas().refresh()

            # ------create map item in the layout_---------------------------------------------------------------------------------------------

            layers2 = QgsProject.instance().mapLayersByName('Site')
            layer2 = layers2[0]

            project = QgsProject.instance()
            manager = project.layoutManager()
            layoutName = 'Map 2 - Neighbourhood & Most Important Journey'
            layouts_list = manager.printLayouts()

            # removes dublicate layers produced
            for layout in layouts_list:
                if layout.name() == layoutName:
                    manager.removeLayout(layout)

            layout = QgsPrintLayout(project)
            layout.initializeDefaults()
            layout.setName(layoutName)
            manager.addLayout(layout)
            canvas = iface.mapCanvas()

            # Creating a frame around map and legend - min/max in mm in layout
            xmin = 5
            xmax = 292
            ymin = 2
            ymax = 208
            polygon = QPolygonF()
            polygon.append(QPointF(xmin, ymin))
            polygon.append(QPointF(xmax, ymin))
            polygon.append(QPointF(xmax, ymax))
            polygon.append(QPointF(xmin, ymax))

            # Create the polygon from nodes
            polygonItem = QgsLayoutItemPolygon(polygon, layout)

            # Add to the layout
            layout.addItem(polygonItem)

            Map2 = QgsLayoutItemMap.create(layout)
            Map2.setRect(10, 10, 210, 90)
            ms = QgsMapSettings()
            ms.setLayers([layer2])

            # adding map to layout
            Map2.setFrameEnabled(True)
            Map2.setExtent(canvas.extent())
            Map2.setScale(40000, forceUpdate=1)

            layout.addLayoutItem(Map2)

            Map2.attemptMove(QgsLayoutPoint(4, 2, QgsUnitTypes.LayoutMillimeters))
            # ============================(Width, Length)
            Map2.attemptResize(QgsLayoutSize(215, 206, QgsUnitTypes.LayoutMillimeters))

            # addding custom arrow
            picture2 = QgsLayoutItemPicture(layout)
            picture2.update()
            layout.addLayoutItem(picture2)
            picture2.setPicturePath(
                r"\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\Active Travel Zones\Map Template Items\NorthArrow_Red.png")
            picture2.attemptMove(QgsLayoutPoint(5, 3, QgsUnitTypes.LayoutMillimeters))
            picture2.setResizeMode(QgsLayoutItemPicture.FrameToImageSize)

            # adding scalebar
            scalebar = QgsLayoutItemScaleBar(layout)
            scalebar.setStyle('Single Box')
            scalebar.setUnits(QgsUnitTypes.DistanceKilometers)
            scalebar.setNumberOfSegments(4)
            scalebar.setNumberOfSegmentsLeft(0)
            scalebar.setUnitsPerSegment(0.5)
            scalebar.setLinkedMap(Map2)
            scalebar.setUnitLabel('km')
            scalebar.setFont(QFont('Arial', 8))
            scalebar.refresh()
            layout.addLayoutItem(scalebar)
            # ============================------(Width, Length)
            scalebar.attemptMove(QgsLayoutPoint(160, 196, QgsUnitTypes.LayoutMillimeters))
            scalebar.applyDefaultSize
            scalebar.refresh()

            # adding title
            title = QgsLayoutItemLabel(layout)
            title.setBackgroundEnabled(True)
            title.setText('Map 2 - Neighbourhood & Most Important Journeys')
            title.setFont(QFont('Arial', 20))
            title.setFontColor(QColor('red'))
            title.adjustSizeToText()
            layout.addLayoutItem(title)
            # ============================---(Width, Length)
            title.attemptMove(QgsLayoutPoint(30, 3, QgsUnitTypes.LayoutMillimeters))
            title.refresh()

            # adding WSP logo
            picture = QgsLayoutItemPicture(layout)
            picture.update()
            layout.addLayoutItem(picture)
            picture.setPicturePath(
                r"\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\Active Travel Zones\Map Template Items\wsp_logo.png")
            picture.attemptMove(QgsLayoutPoint(5, 195, QgsUnitTypes.LayoutMillimeters))
            picture.setResizeMode(QgsLayoutItemPicture.FrameToImageSize)

            # adding legend and layers into legend
            legend = QgsLayoutItemLegend(layout)
            legend.setLinkedMap(Map2)
            legend.refresh()
            layouts_check = QgsProject.instance().layoutManager()

            legend.setTitle("Key:")
            newFont = QFont("Aerial", 8)
            LargeFont = QFont("Aerial", 12)
            legend.setStyleFont(QgsLegendStyle.Title, LargeFont)
            legend.setStyleFont(QgsLegendStyle.Subgroup, newFont)
            legend.setStyleFont(QgsLegendStyle.SymbolLabel, newFont)
            # legend.setFrameEnabled(True)

            # position legend
            layout.addLayoutItem(legend)
            # ============================---(Width, Length)
            legend.attemptMove(QgsLayoutPoint(221, 4, QgsUnitTypes.LayoutMillimeters))
            legend.attemptResize(QgsLayoutSize(20, 206, QgsUnitTypes.LayoutMillimeters))

            legend.refresh()

            # ----- Export map as PDF and PNG--------------------------------

            OutMaps = projectGISFolder + "\\" + folders[4] + "\\"
            fn = OutMaps + "Map 2 - Neighbourhood & Most Important Journeys.png"
            exporter = QgsLayoutExporter(layout)
            exporter.exportToImage(fn, QgsLayoutExporter.ImageExportSettings())

            layout.refresh()
            project2.write()
            project2.clear()

            # ----------Creating Map 3----------------------------------------------------------------------------------------

            Mapout = projectGISFolder + "\\" + folders[3] + "\\"
            project3 = QgsProject.instance()
            project3.setCrs(QgsCoordinateReferenceSystem(3857))
            project3.setFileName(Mapout + Map3name)

            MapSite = BNG_Sub_Folder_make + BNGFOLDER[0] + "\\" + "Site Location.shp"
            Map3Layers = projectGISFolder + "\\" + folders[2] + "\\" + CLIP_WALK_10[0] + "\\"
            Site = QgsVectorLayer(MapSite, "Site", "ogr")
            Walk_10_Map = QgsVectorLayer(CH_WALK_10, "Approximate 10 minute walk time from site", "ogr")

            mapbox_basemap = 'type=xyz&url=https://api.mapbox.com/styles/v1/chris-ryan-wsp/ck3r54pn8041b1cmzvdaxv1qc/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoiY2hyaXMtcnlhbi13c3AiLCJhIjoiY2szazRzNnhqMG8xZTNjb2N5NDVqeTV5MSJ9.hpX0Il1EIUT5pc7v-Z7lSQ'
            rlayer = QgsRasterLayer(mapbox_basemap, 'Mapbox', 'wms')
            QgsProject.instance().addMapLayer(rlayer)

            Layerlist3 = []
            for item in os.listdir(Map3Layers):
                if item[-3:] == 'shp':
                    Layerlist3.append(item)
            for layer in Layerlist3:
                shplayer = iface.addVectorLayer(Map3Layers + "//" + layer, "", "ogr")
                shplayer.setCrs(QgsCoordinateReferenceSystem(27700))
                project3.addMapLayer(shplayer)

            project3.addMapLayer(Site)
            project3.addMapLayer(Walk_10_Map)
            ex = Walk_10_Map.extent()

            # transforms layer projection

            proj = QgsProject.instance()
            if Site.crs().authid() != proj.crs().authid():
                tr = QgsCoordinateTransform(Site.crs(), proj.crs(), proj)
                ex = tr.transform(ex)
            if shplayer.crs().authid() != proj.crs().authid():
                tr = QgsCoordinateTransform(shplayer.crs(), proj.crs(), proj)
            Layermap = QgsProject.instance().mapLayers()
            RemoveLayers3 = []
            for name, layer in Layermap.items():
                if layer.isValid():
                    if layer.type() == QgsMapLayer.VectorLayer:
                        if layer.featureCount() == 0:
                            RemoveLayers3.append(layer.id())
            if len(RemoveLayers3) > 0:
                QgsProject.instance().removeMapLayers(RemoveLayers3)

            # Add a small space/border on each side of the layer
            hborder = ex.height() / 70
            wborder = ex.width() / 70
            ex.set(ex.xMinimum() - wborder,
                   ex.yMinimum() - hborder,
                   ex.xMaximum() + wborder,
                   ex.yMaximum() + hborder,
                   )

            iface.mapCanvas().setExtent(ex)
            iface.mapCanvas().refresh()

            # ------create map item in the layout_---------------------------------------------------------------------------------------------

            layers3 = QgsProject.instance().mapLayersByName('Site')
            layer3 = layers3[0]

            project = QgsProject.instance()
            manager = project.layoutManager()
            layoutName = 'Map 3 - Neighbourhood Safety'
            layouts_list = manager.printLayouts()

            # removes dublicate layers produced
            for layout in layouts_list:
                if layout.name() == layoutName:
                    manager.removeLayout(layout)

            layout = QgsPrintLayout(project)
            layout.initializeDefaults()
            layout.setName(layoutName)
            manager.addLayout(layout)
            canvas = iface.mapCanvas()

            # Creating a frame around map and legend - min/max in mm in layout
            xmin = 5
            xmax = 292
            ymin = 2
            ymax = 208
            polygon = QPolygonF()
            polygon.append(QPointF(xmin, ymin))
            polygon.append(QPointF(xmax, ymin))
            polygon.append(QPointF(xmax, ymax))
            polygon.append(QPointF(xmin, ymax))

            # Create the polygon from nodes
            polygonItem = QgsLayoutItemPolygon(polygon, layout)

            # Add to the layout
            layout.addItem(polygonItem)

            Map3 = QgsLayoutItemMap.create(layout)
            Map3.setRect(10, 10, 210, 90)
            ms = QgsMapSettings()
            ms.setLayers([layer3])

            # adding map to layout
            Map3.setFrameEnabled(True)
            Map3.setExtent(canvas.extent())
            Map3.setScale(20000, forceUpdate=1)

            layout.addLayoutItem(Map3)

            Map3.attemptMove(QgsLayoutPoint(4, 2, QgsUnitTypes.LayoutMillimeters))
            # ============================(Width, Length)
            Map3.attemptResize(QgsLayoutSize(215, 206, QgsUnitTypes.LayoutMillimeters))

            # addding custom arrow
            picture2 = QgsLayoutItemPicture(layout)
            picture2.update()
            layout.addLayoutItem(picture2)
            picture2.setPicturePath(
                r"\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\Active Travel Zones\Map Template Items\NorthArrow_Red.png")
            picture2.attemptMove(QgsLayoutPoint(5, 3, QgsUnitTypes.LayoutMillimeters))
            picture2.setResizeMode(QgsLayoutItemPicture.FrameToImageSize)

            # adding scalebar
            scalebar = QgsLayoutItemScaleBar(layout)
            scalebar.setStyle('Single Box')
            scalebar.setUnits(QgsUnitTypes.DistanceKilometers)
            scalebar.setNumberOfSegments(2)
            scalebar.setNumberOfSegmentsLeft(0)
            scalebar.setUnitsPerSegment(0.5)
            scalebar.setLinkedMap(Map3)
            scalebar.setUnitLabel('km')
            scalebar.setFont(QFont('Arial', 8))
            scalebar.refresh()
            layout.addLayoutItem(scalebar)
            # ============================------(Width, Length)
            scalebar.attemptMove(QgsLayoutPoint(160, 196, QgsUnitTypes.LayoutMillimeters))
            scalebar.applyDefaultSize
            scalebar.refresh()

            # adding title
            title = QgsLayoutItemLabel(layout)
            title.setBackgroundEnabled(True)
            title.setText('Map 3 - Neighbourhood Safety')
            title.setFont(QFont('Arial', 20))
            title.setFontColor(QColor('red'))
            title.adjustSizeToText()
            layout.addLayoutItem(title)
            # ============================---(Width, Length)
            title.attemptMove(QgsLayoutPoint(85, 3, QgsUnitTypes.LayoutMillimeters))
            title.refresh()

            # adding WSP logo
            picture = QgsLayoutItemPicture(layout)
            picture.update()
            layout.addLayoutItem(picture)
            picture.setPicturePath(
                r"\\uk.wspgroup.com\central data\Discipline Management\Development\01 Service Lines\Smart Consulting\Digital\Data & Analysis\Active Travel Zones\Map Template Items\wsp_logo.png")
            picture.attemptMove(QgsLayoutPoint(5, 195, QgsUnitTypes.LayoutMillimeters))
            picture.setResizeMode(QgsLayoutItemPicture.FrameToImageSize)

            # adding legend and layers into legend
            legend = QgsLayoutItemLegend(layout)
            legend.setLinkedMap(Map3)
            legend.refresh()
            layouts_check = QgsProject.instance().layoutManager()
            legend.setTitle("Key:")
            newFont = QFont("Aerial", 8)
            LargeFont = QFont("Aerial", 12)
            legend.setStyleFont(QgsLegendStyle.Title, LargeFont)
            legend.setStyleFont(QgsLegendStyle.Subgroup, newFont)
            legend.setStyleFont(QgsLegendStyle.SymbolLabel, newFont)
            layout.addLayoutItem(legend)
            # ============================---(Width, Length)
            legend.attemptMove(QgsLayoutPoint(221, 4, QgsUnitTypes.LayoutMillimeters))
            legend.attemptResize(QgsLayoutSize(20, 206, QgsUnitTypes.LayoutMillimeters))
            legend.refresh()

            # ----- Export map as PDF and PNG--------------------------------

            OutMaps = projectGISFolder + "\\" + folders[4] + "\\"
            fn = OutMaps + "Map 3 - Neighbourhood Safety.png"
            exporter = QgsLayoutExporter(layout)
            exporter.exportToImage(fn, QgsLayoutExporter.ImageExportSettings())

            layout.refresh()
            project3.write()
            project3.clear()

            iface.messageBar().pushMessage("Tool completed, open project folder", level=3)
            # add delay
